In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [3]:
df = pd.read_csv("organizations-100.csv")

In [5]:
df.head()

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
0,1,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,2,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,3,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,4,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,5,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Index                100 non-null    int64
 1   Organization Id      100 non-null    object
 2   Name                 100 non-null    object
 3   Website              100 non-null    object
 4   Country              100 non-null    object
 5   Description          100 non-null    object
 6   Founded              100 non-null    int64
 7   Industry             100 non-null    object
 8   Number of employees  100 non-null    int64
dtypes: int64(3), object(6)
memory usage: 7.2+ KB

In [7]:
df.shape

(100, 9)

In [8]:
df.describe(include="all")

,Index,Organization Id,Name,Website,Country,Description,Founded,Industry,Number of employees
count,100.000000,100,100,100,100,100,100.000000,100,100.000000
unique,NaN,100,100,100,84,100,NaN,72,NaN
top,NaN,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Benin,Horizontal empowering knowledgebase,NaN,Plastics,NaN
freq,NaN,1,1,1,3,1,NaN,4,NaN
mean,50.500000,NaN,NaN,NaN,NaN,NaN,1995.410000,NaN,4964.860000
std,29.011492,NaN,NaN,NaN,NaN,NaN,15.744228,NaN,2850.859799
min,1.000000,NaN,NaN,NaN,NaN,NaN,1970.000000,NaN,236.000000
25%,25.750000,NaN,NaN,NaN,NaN,NaN,1983.500000,NaN,2741.250000
50%,50.500000,NaN,NaN,NaN,NaN,NaN,1995.000000,NaN,4941.500000
75%,75.250000,NaN,NaN,NaN,NaN,NaN,2010.250000,NaN,7558.000000
max,100.000000,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,9995.000000

In [9]:
print("\nDuplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [10]:
df = df.drop_duplicates()

In [11]:
assert df.duplicated().sum() == 0
print("Duplicates removed successfully!")

Duplicates removed successfully!

In [12]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

In [13]:
df.head()

,index,organization_id,name,website,country,description,founded,industry,number_of_employees
0,1,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,2,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,3,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,4,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,5,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870

In [18]:
print("\nMissing Values Before Cleaning:")
print(df.isna().sum())

Missing Values Before Cleaning:
index                  0
organization_id        0
name                   0
website                0
country                0
description            0
founded                0
industry               0
number_of_employees    0
dtype: int64

In [19]:
assert df.isna().sum().sum() == 0
print("Missing values handled successfully!")

Missing values handled successfully!

In [20]:
for col in df.columns:
    if "date" in col:
        df[col] = pd.to_datetime(df[col], errors="coerce")

In [21]:
for col in df.columns:
    if df[col].dtype == "object":
        try:
            df[col] = pd.to_numeric(df[col].str.replace(",", ""), errors="ignore")
        except:
            pass

C:\Users\Mukta\AppData\Local\Temp\ipykernel_8272\4021060637.py:4: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col].str.replace(",", ""), errors="ignore")

In [22]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.lower().str.strip()

In [23]:
df.replace({
    "usa": "united states",
    "u.s.a": "united states",
    "uk": "united kingdom"
}, inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                100 non-null    float64
 1   organization_id      100 non-null    object
 2   name                 100 non-null    object
 3   website              100 non-null    object
 4   country              100 non-null    object
 5   description          100 non-null    object
 6   founded              100 non-null    float64
 7   industry             100 non-null    object
 8   number_of_employees  100 non-null    float64
dtypes: float64(3), object(6)
memory usage: 7.2+ KB

In [25]:
df.to_csv("cleaned_organizations.csv", index=False)

print("\n✅ Cleaning Completed Successfully!")
print("Cleaned file saved as: cleaned_organizations.csv")

✅ Cleaning Completed Successfully!
Cleaned file saved as: cleaned_organizations.csv